# Generated by Django 4.2 on 2023-04-12 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor_id', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('work_our_start', models.CharField(max_length=50)),
                ('work_our_end', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_id', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('company_designation', models.CharField(max_length=200)),
                ('date_of_appointment', models.DateTimeField(default=None)),
                ('insurance', models.CharField(choices=[('comprehensive', 'comprehensive'), ('semi comprehensive', 'semi comprehensive'), ('no insurance', 'no insurance')], default='no insurance', max_length=50)),
                ('work_our_start', models.CharField(max_length=50)),
                ('work_our_end', models.CharField(max_length=50)),
                ('confirmed', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='core.doctor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_id', models.CharField(max_length=200)),
                ('total', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=12)),
                ('deduction_percentage', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=12)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='core.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
